require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RemoteProjectsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RemoteProject. As you add validations to RemoteProject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RemoteProjectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all remote_projects as @remote_projects" do
      remote_project = RemoteProject.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:remote_projects)).to eq([remote_project])
    end
  end

  describe "GET #show" do
    it "assigns the requested remote_project as @remote_project" do
      remote_project = RemoteProject.create! valid_attributes
      get :show, {:id => remote_project.to_param}, valid_session
      expect(assigns(:remote_project)).to eq(remote_project)
    end
  end

  describe "GET #new" do
    it "assigns a new remote_project as @remote_project" do
      get :new, {}, valid_session
      expect(assigns(:remote_project)).to be_a_new(RemoteProject)
    end
  end

  describe "GET #edit" do
    it "assigns the requested remote_project as @remote_project" do
      remote_project = RemoteProject.create! valid_attributes
      get :edit, {:id => remote_project.to_param}, valid_session
      expect(assigns(:remote_project)).to eq(remote_project)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RemoteProject" do
        expect {
          post :create, {:remote_project => valid_attributes}, valid_session
        }.to change(RemoteProject, :count).by(1)
      end

      it "assigns a newly created remote_project as @remote_project" do
        post :create, {:remote_project => valid_attributes}, valid_session
        expect(assigns(:remote_project)).to be_a(RemoteProject)
        expect(assigns(:remote_project)).to be_persisted
      end

      it "redirects to the created remote_project" do
        post :create, {:remote_project => valid_attributes}, valid_session
        expect(response).to redirect_to(RemoteProject.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved remote_project as @remote_project" do
        post :create, {:remote_project => invalid_attributes}, valid_session
        expect(assigns(:remote_project)).to be_a_new(RemoteProject)
      end

      it "re-renders the 'new' template" do
        post :create, {:remote_project => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested remote_project" do
        remote_project = RemoteProject.create! valid_attributes
        put :update, {:id => remote_project.to_param, :remote_project => new_attributes}, valid_session
        remote_project.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested remote_project as @remote_project" do
        remote_project = RemoteProject.create! valid_attributes
        put :update, {:id => remote_project.to_param, :remote_project => valid_attributes}, valid_session
        expect(assigns(:remote_project)).to eq(remote_project)
      end

      it "redirects to the remote_project" do
        remote_project = RemoteProject.create! valid_attributes
        put :update, {:id => remote_project.to_param, :remote_project => valid_attributes}, valid_session
        expect(response).to redirect_to(remote_project)
      end
    end

    context "with invalid params" do
      it "assigns the remote_project as @remote_project" do
        remote_project = RemoteProject.create! valid_attributes
        put :update, {:id => remote_project.to_param, :remote_project => invalid_attributes}, valid_session
        expect(assigns(:remote_project)).to eq(remote_project)
      end

      it "re-renders the 'edit' template" do
        remote_project = RemoteProject.create! valid_attributes
        put :update, {:id => remote_project.to_param, :remote_project => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested remote_project" do
      remote_project = RemoteProject.create! valid_attributes
      expect {
        delete :destroy, {:id => remote_project.to_param}, valid_session
      }.to change(RemoteProject, :count).by(-1)
    end

    it "redirects to the remote_projects list" do
      remote_project = RemoteProject.create! valid_attributes
      delete :destroy, {:id => remote_project.to_param}, valid_session
      expect(response).to redirect_to(remote_projects_url)
    end
  end

end
